### ISSUE TITLE
服务器端运行 出现document is not defined

### ISSUE THREAD

**Issue by liming84525** [uxcore/uxcore-table#176]
[dev:server] /home/liming/IdeaProjects/reduxtest/node_modules/uxcore-tree/build/Tree.js:37
[2] var supportSVG = document.implementation.hasFeature('http://www.w3.org/TR/SVG11/feature#BasicStructure', '1.1');
[2]                  ^
[2] [dev:server] ReferenceError: document is not defined
[2]     at Object.<anonymous> (/home/liming/IdeaProjects/reduxtest/node_modules/uxcore-tree/build/Tree.js:37:18)
[2]     at Module._compile (module.js:573:32)
[2]     at Object.Module._extensions..js (module.js:582:10)
[2]     at Module.load (module.js:490:32)
[2]     at tryModuleLoad (module.js:449:12)
[2]     at Function.Module._load (module.js:441:3)
[2]     at Module.require (module.js:500:17)
[2]     at require (internal/module.js:20:19)
[2]     at Object.<anonymous> (/home/liming/IdeaProjects/reduxtest/node_modules/uxcore-tree/build/index.js:11:18)
[2]     at Module._compile (module.js:573:32)
[2] [dev:server] [nodemon] app crashed - waiting for file changes before starting...

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-tree/commit/c89e2ca715d933af34374260f617e27c2cc435f7

reinstall table to solve this problem.
